default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.1
    hidden_units: 128
    lambd: 0.9
    learning_rate: 0.03
    learning_rate_schedule: linear
    max_steps: 10.0e6
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple

#PPO
SpiderBrain:
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.03
            gamma: 0.99
            encoding_size: 512
    trainer: ppo
    lambd: 0.92
    buffer_size: 16384
    batch_size: 4192
    num_epoch: 5
    learning_rate: 0.0003
    learning_rate_schedule: linear
    time_horion: 4196
    max_steps: 15e6
    beta: 0.0005
    epsilon: 0.2
    normalize: false
    num_layers: 3
    hidden_units: 256
    behavioral_cloning:
        demo_path: ./Demos/updatedwalk.demo
        strength: 0.5
        steps: 10000
    
#SAC
SpiderBrainSAC:
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.03
            gamma: 0.99
            encoding_size: 512
    trainer: sac
    batch_size: 4196
    buffer_init_steps: 50000
    buffer_size: 300000
    init_entcoef: 1
    train_interval: 10
    tau: 0.005
    learning_rate: 1e-4
    max_steps: 10e6
    time_horizon: 512
    num_layers: 3
    hidden_units: 256
    num_update: 1
    #use_recurrent: true
    #sequence_length: 4
    #memory_size: 64

ppa_old:
    normalize: false
    lambd: 0.9
    learning_rate: 1e-3
    num_layers: 6
    hidden_units: 64
    beta: 1e-1
    epsilon: 0.3
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 3