behaviors:
  SpiderBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      beta: 5.0e-3
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-3
      learning_rate_schedule: linear
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000